package org.liferay.lifebringer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GameScore service. Represents a row in the &quot;lifebringer_GameScore&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.liferay.lifebringer.model.impl.GameScoreModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.liferay.lifebringer.model.impl.GameScoreImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GameScore
 * @see org.liferay.lifebringer.model.impl.GameScoreImpl
 * @see org.liferay.lifebringer.model.impl.GameScoreModelImpl
 * @generated
 */
public interface GameScoreModel extends BaseModel<GameScore>, GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a game score model instance should use the {@link GameScore} interface instead.
     */

    /**
     * Returns the primary key of this game score.
     *
     * @return the primary key of this game score
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this game score.
     *
     * @param primaryKey the primary key of this game score
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the game ID of this game score.
     *
     * @return the game ID of this game score
     */
    public long getGameId();

    /**
     * Sets the game ID of this game score.
     *
     * @param gameId the game ID of this game score
     */
    public void setGameId(long gameId);

    /**
     * Returns the group ID of this game score.
     *
     * @return the group ID of this game score
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this game score.
     *
     * @param groupId the group ID of this game score
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this game score.
     *
     * @return the company ID of this game score
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this game score.
     *
     * @param companyId the company ID of this game score
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this game score.
     *
     * @return the user ID of this game score
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this game score.
     *
     * @param userId the user ID of this game score
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this game score.
     *
     * @return the user uuid of this game score
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this game score.
     *
     * @param userUuid the user uuid of this game score
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this game score.
     *
     * @return the user name of this game score
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this game score.
     *
     * @param userName the user name of this game score
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this game score.
     *
     * @return the create date of this game score
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this game score.
     *
     * @param createDate the create date of this game score
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this game score.
     *
     * @return the modified date of this game score
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this game score.
     *
     * @param modifiedDate the modified date of this game score
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the game time of this game score.
     *
     * @return the game time of this game score
     */
    public int getGameTime();

    /**
     * Sets the game time of this game score.
     *
     * @param gameTime the game time of this game score
     */
    public void setGameTime(int gameTime);

    /**
     * Returns the game score of this game score.
     *
     * @return the game score of this game score
     */
    public int getGameScore();

    /**
     * Sets the game score of this game score.
     *
     * @param gameScore the game score of this game score
     */
    public void setGameScore(int gameScore);

    /**
     * Returns the red zombies killed of this game score.
     *
     * @return the red zombies killed of this game score
     */
    public int getRedZombiesKilled();

    /**
     * Sets the red zombies killed of this game score.
     *
     * @param redZombiesKilled the red zombies killed of this game score
     */
    public void setRedZombiesKilled(int redZombiesKilled);

    /**
     * Returns the green zombies killed of this game score.
     *
     * @return the green zombies killed of this game score
     */
    public int getGreenZombiesKilled();

    /**
     * Sets the green zombies killed of this game score.
     *
     * @param greenZombiesKilled the green zombies killed of this game score
     */
    public void setGreenZombiesKilled(int greenZombiesKilled);

    /**
     * Returns the missed of this game score.
     *
     * @return the missed of this game score
     */
    public int getMissed();

    /**
     * Sets the missed of this game score.
     *
     * @param missed the missed of this game score
     */
    public void setMissed(int missed);

    /**
     * Returns the fired of this game score.
     *
     * @return the fired of this game score
     */
    public int getFired();

    /**
     * Sets the fired of this game score.
     *
     * @param fired the fired of this game score
     */
    public void setFired(int fired);

    /**
     * Returns the level of this game score.
     *
     * @return the level of this game score
     */
    public int getLevel();

    /**
     * Sets the level of this game score.
     *
     * @param level the level of this game score
     */
    public void setLevel(int level);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(GameScore gameScore);

    @Override
    public int hashCode();

    @Override
    public CacheModel<GameScore> toCacheModel();

    @Override
    public GameScore toEscapedModel();

    @Override
    public GameScore toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
