package org.liferay.lifebringer.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.liferay.lifebringer.model.GameScore;
import org.liferay.lifebringer.service.GameScoreLocalServiceUtil;

/**
 * The extended model base implementation for the GameScore service. Represents a row in the &quot;lifebringer_GameScore&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GameScoreImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GameScoreImpl
 * @see org.liferay.lifebringer.model.GameScore
 * @generated
 */
public abstract class GameScoreBaseImpl extends GameScoreModelImpl
    implements GameScore {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a game score model instance should use the {@link GameScore} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            GameScoreLocalServiceUtil.addGameScore(this);
        } else {
            GameScoreLocalServiceUtil.updateGameScore(this);
        }
    }
}
